### ISSUE TITLE
BLE interface

### ISSUE THREAD

**Issue by osresearch** [hollyhudson/erg-interface#3]
We need BLE!

**Comment by ellvinib** [comment]
Why not using the BLE of the console ? And connect and retrieve that information ?

**Comment by osresearch** [comment]
The console has *very* bad estimates for power and distance: as far as I can tell it only looks at how far you've pulled the cable, nothing about how fast or frequently.  Instead we've completely disconnected their head unit and have everything estimated by the esp board based on some simplified fluid drag equations.

And instead of outputting over BLE, we're now publishing a local website via websockets, as well as pushing into our grafana dashboard system.  So, it turns out, we don't need BLE...
